services:
  - type: web
    name: secure-proxy
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: TARGET_URL
        value: https://pse.pwm435.space
      - key: NODE_ENV
        value: production
    healthCheckPath: /3co
